# Generated by Django 6.0.1 on 2026-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdataset',
            name='file_name',
            field=models.CharField(default='old_file.csv', max_length=255),
            preserve_default=False,
        ),
    ]
