# Generated by Django 6.0.1 on 2026-02-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_equipmentdataset_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdataset',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
