# Generated by Django 6.0.1 on 2026-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_equipmentdataset_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdataset',
            name='summary',
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='avg_flowrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='avg_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='avg_temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentdataset',
            name='total_equipment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
