# Generated by Django 6.0.1 on 2026-02-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_equipmentdata_uploadedfile_delete_equipmentdataset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
